version: "3.7"

services:
    # image project
    curso_api_cache:
        container_name: api_cache_laravel-9
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - api_cache
    
    # nginx
    nginx:
        container_name: api_cache_nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8005:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - api_cache

    # db mysql
    mysql:
        container_name: api_cache_mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3322:3306"
        networks: 
            - api_cache

    # queue
    queue:
        container_name: api_cache_queue
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - curso_api_cache
        networks: 
            - api_cache

    # redis
    redis:
        container_name: api_cache_redis
        image: redis:latest
        networks: 
            - api_cache

networks: 
    api_cache:
        driver: bridge